version: "3.8"

services:
  frontend:
    build:
      context: ./front # front 디렉토리의 Dockerfile 기준으로 빌드
    ports:
      - "5173:5173" # 외부 → 컨테이너 포트 매핑
    depends_on:
      - backend # 백엔드가 먼저 실행되어야 함

  backend:
    build:
      context: ./back # back 디렉토리의 Dockerfile 기준으로 빌드
    ports:
      - "8000:8000" # FastAPI 기본 포트
    depends_on:
      - db # DB가 먼저 실행되어야 함

  db:
    image: mysql:8.0 # MySQL 공식 이미지
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: counter_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306" # MySQL 기본 포트
    volumes:
      - db_data:/var/lib/mysql # DB 데이터가 날아가지 않도록 volume 설정

volumes:
  db_data:
