services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: uss02039!!
      MYSQL_DATABASE: myappdb
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: uss02039!!
      MYSQL_DATABASE: myappdb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: