version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: mydb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: counterdb
      MYSQL_USER: counteruser
      MYSQL_PASSWORD: counterpw
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      DB_HOST: db
      DB_USER: counteruser
      DB_PASSWORD: counterpw
      DB_NAME: counterdb
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db_data: 