version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: numbers_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ment-net

  backend:
    build: ./backend
    container_name: fastapi_backend
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      MYSQL_DB: numbers_db
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - ment-net

  frontend:
    build: ./frontend
    container_name: react_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - ment-net

volumes:
  db_data:

networks:
  ment-net:
    driver: bridge 