CREATE DATABASE IF NOT EXISTS testdb
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_general_ci;

USE testdb;

CREATE TABLE IF NOT EXISTS logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  value TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
